# Generated by Django 3.0.4 on 2020-04-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=50)),
                ('siren', models.IntegerField()),
                ('results', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
